### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by schlembo** [glyptodon/guacamole-proxy-authrequest#2]
Hi,
can you give me a short instructions how to build this for the actual 1.5.1 version, so that i get a ready to work .jar file.

I tried multiple times but always get:
`{"message":"No such resource.","translatableMessage":{"key":"APP.TEXT_UNTRANSLATED","variables":{"MESSAGE":"No such resource."}},"statusCode":null,"expected":null,"type":"NOT_FOUND"}`

Thank u a lot!

**Comment by mike-jumper** [comment]
There are no incompatibilities between this extension and any release since 1.0.0, including 1.5.1. It should work without any modification.
